services:

  whisper-en:
    image: rhasspy/wyoming-whisper
    container_name: whisper-en
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - ROCM_VISIBLE_DEVICES=0
    ports:
      - "10300:10300"
    volumes:
      - /mnt/docker_DATA/whisper:/data
    command: >
      --model tiny-int8
      --language en

  whisper-fr:
    image: rhasspy/wyoming-whisper
    container_name: whisper-fr
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - ROCM_VISIBLE_DEVICES=0
    ports:
      - "10301:10300"
    volumes:
      - /mnt/docker_DATA/whisper:/data
    command: >
      --model tiny-int8
      --language fr

  piper-en:
    image: rhasspy/wyoming-piper
    container_name: piper-en
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - ROCM_VISIBLE_DEVICES=0
    ports:
      - "10200:10200"
    volumes:
      - /mnt/docker_DATA/piper:/data
    command: >
      --voice en_US-amy-medium

  piper-fr:
    image: rhasspy/wyoming-piper
    container_name: piper-fr
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - ROCM_VISIBLE_DEVICES=0
    ports:
      - "10201:10200"
    volumes:
      - /mnt/docker_DATA/piper:/data
    command: >
      --voice fr-tom-medium
