services:
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper:latest
    # Commande minimale pour démarrer sans arguments
    command: /bin/bash -c "sleep infinity"
    volumes:
      - /docker_DATA/whisper-data:/data
      - /docker_DATA/scripts:/workspace/scripts
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    ports:
      - 127.0.0.1:10300:10300

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper:latest
    # Commande minimale pour démarrer sans arguments
    command: /bin/bash -c "sleep infinity"
    volumes:
      - /docker_DATA/piper-data:/data
      - /docker_DATA/scripts:/workspace/scripts
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    ports:
      - 127.0.0.1:10200:10200

networks:
  default:
    driver: bridge
